Repository KarimAl-Rashdan/fitlit, pull requests merged in 2023-01, with the labels that each got.

#18 Changed file names for sleepClass and User Class
  dist/index.html
  src/Sleep.js
  src/User.js
  src/UserRepository.js
  src/scripts.js
Labels: documentation

#21 Feature/fetch error handler
  dist/index.html
  src/Sleep.js
  src/SleepRepository.js
  src/User.js
  src/UserRepository.js
  src/scripts.js
  test/Hydration-test.js
  test/HydrationRepository-test.js
  test/Sleep-test.js
  test/SleepRepository-test.js
  test/User-Test.js
  test/UserRepository-test.js
Labels: enhancement, JavaScript, API/FETCH/POST

#24 Feature/activity repository
  src/ActivityRepository.js
  src/HydrationRepository.js
  src/data/sample-acitvity.js
  src/scripts.js
  test/ActivityRepository-test.js
  test/HydrationRepository-test.js
  test/Sleep-test.js
  test/SleepRepository-test.js
  test/User-Test.js
  test/UserRepository-test.js
Labels: documentation, enhancement, TDD, JavaScript

#27 Feature/build post req
  dist/index.html
  src/ActivityRepository.js
  src/HydrationRepository.js
  src/SleepRepository.js
  src/css/styles.css
  src/scripts.js
  test/SleepRepository-test.js
Labels: bug, enhancement, TDD, JavaScript, API/FETCH/POST

#30 Feature/updated read me
  README.md
  dist/images/turing-logo.png
  dist/index.html
  friends2.png.sb-e1db2d34-6SgGBL
  login.jpeg.sb-e1db2d34-ILJReb
  loginimage.png
  src/ActivityRepository.js
  src/HydrationRepository.js
  src/SleepRepository.js
  src/css/styles.css
  src/images/friends.png
  src/images/friends2.jpg
  src/images/intro.jpg
  src/images/logo.png
  src/images/runner.jpg
  src/images/turing-logo.png
  src/scripts.js
  test/HydrationRepository-test.js
Labels: documentation, Accessibility

#32 Feature/weekly hydro update
  src/HydrationRepository.js
  src/data/hydration-data.js
  src/scripts.js
  test/HydrationRepository-test.js
Labels: documentation, enhancement, TDD, JavaScript
